spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opensims?createDatabaseIfNotExist=true
    username: dantawalli
    password: p@55w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    user:
      name: admin
      password: admin
  data:
    rest:
      base-path: /api
logging:
    level:
     org.springframework.security: DEBUG
#jwt:
#  secret: your-secure-jwt-secret
#  expiration:
#    ms: 3600000 # 1 hour in milliseconds
server:
  ssl:
    enabled: true
    key-store-type: PKCS12 # Specify the type of keystore (e.g., JKS, PKCS12)
    key-store: classpath:certificate.p12 # Path to the keystore file
    key-store-password: D@ntawall1 # Keystore password
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true



