spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opensims
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    user:
      name: admin
      password: admin
logging:
    level:
     org.springframework.security: DEBUG


